#!/usr/bin/env bash
#%# family=manual

slave=`ssh -p 18000 postgres@10.8.0.1 'psql -p 13110 postgres -A -t -c "SELECT pg_is_in_recovery();"'`

case $1 in
    autoconf)
        echo yes
        exit 0
        ;;
    config)
        echo graph_category PostgreSQL
        echo graph_title PostgreSQL Streaming Replication
        if [[ $slave == "t" ]]; then
            echo 'graph_args --base 1000 -r -l 0'
            echo delay_s.label Replication Delay \(seconds\)
            echo graph_scale no
        fi
        exit 0
        ;;
esac

if [[ $slave == "t" ]]; then
    # Slave
    echo -n "delay_s.value "
    ssh -p 18000 postgres@10.8.0.1 'psql -p 13110 postgres -A -t -c "SELECT CASE WHEN pg_last_wal_receive_lsn() = pg_last_wal_replay_lsn() THEN 0 ELSE EXTRACT (EPOCH FROM now() - pg_last_xact_replay_timestamp()) END;"' | tr -d "\n"
fi

exit 0
